function [D] = brainedgedist(brain,vsize,varargin)
isosize  = size(brain).*vsize;
[y,x,z]  = ndgrid(linspace(1,size(brain,1),isosize(1)),...
                 linspace(1,size(brain,2),isosize(2)),...
                 linspace(1,size(brain,3),isosize(3)));
isobrain = interpn(double(brain),y,x,z,varargin{:});
isoD     = bwdist(~isobrain);
[y,x,z]  = ndgrid(linspace(1,isosize(1),size(brain,1)),...
                 linspace(1,isosize(2),size(brain,2)),...
                 linspace(1,isosize(3),size(brain,3)));
D        = interpn(double(isoD),y,x,z,'linear');